### ISSUE TITLE
Please update docs with example for running JGen.py 

### ISSUE THREAD

**Issue by anrei0000** [harrison-broadbent/JGen#1]
Hello, this looks interesting and I want to test things out.

I couldn't run the script in under 1 minute so I'm showing what I did. Possibly a simple copy paste example in the docs will help.

![image](https://user-images.githubusercontent.com/4947150/111303328-13f78080-865d-11eb-9cf3-464455f7cf20.png)

**Comment by anrei0000** [comment]
Adding template.txt changes

![image](https://user-images.githubusercontent.com/4947150/111304200-21f9d100-865e-11eb-8a8a-ab71eaf2eaee.png)

**Comment by harrison-broadbent** [comment]
Hey thanks for the feedback. I'll add some more details but make sure you're running it as a python script and not a shell script - 

`
python3 JGen.py
`

Rather than - 

`
./JGen.py
`

**Comment by harrison-broadbent** [comment]
@anrei0000 I just updated the README with a getting started section, hope that helps clarify things a bit. 

Thanks for the feedback and for checking out this project!
